spring:
 data:
   mongodb:
     database: news
     port: 27017
     host: localhost
server:
 port: 8083
 servlet:
    context-path: /newsSourceService
 
logging:
  level:
    org:
      mongodb:
        driver: ERROR
  